/**
 * Differential test: replays the Python reference implementation's command
 * output (fixtures/vectors.json, generated by /tmp/diff/gen_vectors.py from
 * TheMicDiet/chihiros-led-control) through the TypeScript port and asserts
 * byte-for-byte equality.
 *
 * Regenerating the vectors:
 *   cd /tmp/diff && python gen_vectors.py
 *   (copies vectors.json into src/protocol/fixtures/)
 */
import { describe, expect, it } from 'vitest';
import vectors from './fixtures/vectors.json';
import {
  createAddAutoSettingCommand,
  createAutoPointCommand,
  createBaseAuthCommand,
  createDeleteAutoSettingCommand,
  createDoseAuth1Command,
  createDoseAuth2Command,
  createFanAutoModeCommand,
  createManualDoseCommand,
  createQueryStatusCommand,
  createResetAutoSettingsCommand,
  createSetBrightnessCommand,
  createSetFanSpeedCommand,
  createSetTimeCommand,
  createSwitchToAutoModeCommand,
  createSwitchToManualModeCommand,
  createVivid3BluetoothLedCommand,
  createVivid3FanStartStopTempCommand,
  createVivid3TempProtectCommand,
  splitDoseVolumeMl,
  type TimeOfDay,
} from './commands';
import { encodeTimestamp, type MessageId } from './protocol';

interface Vector {
  name: string;
  func: string;
  args: unknown[];
  bytes?: number[];
  high?: number;
  low?: number;
}

function timeOfDay(value: string): TimeOfDay {
  const [hour = 0, minute = 0] = value.split(':').map(Number);
  return { hour, minute };
}

/** Dispatch a reference vector to the equivalent TS command builder. */
function run(vector: Vector): Uint8Array {
  const [a, b] = vector.args as [number, number, ...unknown[]];
  const mid: MessageId = [a, b];
  switch (vector.func) {
    case 'create_base_auth_command':
      return createBaseAuthCommand(mid);
    case 'split_dose_volume_ml':
      return Uint8Array.from(splitDoseVolumeMl(vector.args[0] as number));
    case 'create_dose_auth_1_command':
      return createDoseAuth1Command(mid);
    case 'create_dose_auth_2_command':
      return createDoseAuth2Command(mid);
    case 'create_manual_dose_command':
      return createManualDoseCommand(mid, vector.args[2] as number, vector.args[3] as number);
    case 'create_set_time_command':
      return createSetTimeCommand(mid, new Date(vector.args[2] as string));
    case 'create_set_brightness_command':
      return createSetBrightnessCommand(
        mid,
        vector.args[2] as number,
        vector.args[3] as number,
      );
    case 'create_query_status_command':
      return createQueryStatusCommand(mid);
    case 'create_add_auto_setting_command':
      return createAddAutoSettingCommand(
        mid,
        timeOfDay(vector.args[2] as string),
        timeOfDay(vector.args[3] as string),
        vector.args[4] as number[],
        vector.args[5] as number,
        vector.args[6] as number,
      );
    case 'create_delete_auto_setting_command':
      return createDeleteAutoSettingCommand(
        mid,
        timeOfDay(vector.args[2] as string),
        timeOfDay(vector.args[3] as string),
        vector.args[4] as number,
        vector.args[5] as number,
      );
    case 'create_reset_auto_settings_command':
      return createResetAutoSettingsCommand(mid);
    case 'create_set_fan_speed_command':
      return createSetFanSpeedCommand(mid, vector.args[2] as number);
    case 'create_fan_auto_mode_command':
      return createFanAutoModeCommand(mid);
    case 'create_switch_to_auto_mode_command':
      return createSwitchToAutoModeCommand(mid);
    case 'create_switch_to_manual_mode_command':
      return createSwitchToManualModeCommand(mid);
    case 'create_vivid3_temp_protect_command':
      return createVivid3TempProtectCommand(mid, vector.args[2] as boolean);
    case 'create_vivid3_bluetooth_led_command':
      return createVivid3BluetoothLedCommand(mid, vector.args[2] as boolean);
    case 'create_vivid3_fan_start_stop_temp_command':
      return createVivid3FanStartStopTempCommand(
        mid,
        vector.args[2] as number,
        vector.args[3] as number,
      );
    case 'create_auto_point_command':
      return createAutoPointCommand(
        mid,
        vector.args[2] as number,
        vector.args[3] as number,
        vector.args[4] as number,
        vector.args[5] as boolean,
      );
    case 'encode_timestamp':
      return Uint8Array.from(encodeTimestamp(new Date(vector.args[0] as string)));
    default:
      throw new Error(`Unknown reference function: ${vector.func}`);
  }
}

describe('differential: TS port vs Python reference vectors', () => {
  it('has the expected number of vectors', () => {
    expect(vectors).toHaveLength(36);
  });

  for (const vector of vectors as Vector[]) {
    it(`vector "${vector.name}" (${vector.func})`, () => {
      const expected =
        vector.bytes !== undefined
          ? vector.bytes
          : [vector.high as number, vector.low as number];
      const actual = run(vector);
      expect(Array.from(actual)).toEqual(expected);
    });
  }
});
